# Generated by Django 5.1.7 on 2025-03-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='app.task'),
        ),
    ]
